#ifndef NAMES_H
#define NAMES_H
#include <string>

std::string first_name_male[50]={
    "Simon", "Phuc", "Jude", "Jamil", "Julian"
    "Tanguy","Linus","Anton","Emil", "Elias",
    "Theo","Liam","Felix", "Levin",
    "Julian",
    "Markus",
    "Paul",
    "Jonas",
    "Lukas",
    "Leo",
    "Milo",
    "Jasper",
    "Levi",
    "Philipp",
    "Thomas",
    "Oliver",
    "Mailo",
    "Jan",
    "Rupert",
    "Michael",
    "Noah",
    "Matteo",
    "Tim",
    "Samuel",
    "Finn",
    "Jakob",
    "Lorenz",
    "Max",
    "Kian",
    "Aaron",
    "Alexander",
    "Ben",
    "Moritz",
    "Luan",
    "Leon",
    "Daniel",
    "Luis",
    "Hannes",
    "Jonathan",
    "Marvin",
    "Valentin",
};

std::string first_name_female[50]={
    "Ilknur", "Beatrix", "Nichols", "Nicholson",
    "Ida","Lena", "Mila",
    "Leonie",
    "Lia",
    "Emma",
    "Mia",
    "Lea",
    "Amalia",
    "Ava",
    "Vera",
    "Laura",
    "Juna",
    "Sarah",
    "Johanna",
    "Nora",
    "Nane",
    "Antonia",
    "Amelie",
    "Marie",
    "Leni",
    "Julia",
    "Alina",
    "Anna",
    "Sophie",
    "Isabella",
    "Maria",
    "Elena",
    "Marla",
    "Pia",
    "Noah",
    "Ina",
    "Linn",
    "Malu",
    "Luisa",
    "Lani",
    "Finn",
    "Lilli",
    "Mathilda",
    "Sophia",
    "Nina",
    "Mine",
    "Emily",
    "Viola",
    "Lara",
    "Elina"
};

std::string last_name[50]={
    "Anderson", "Ashwoon", "Aikin", "Bateman", "Bongard",
    "Bowers", "Boyd", "Cannon", "Cast", "Deitz",
    "Dewalt", "Ebner", "Frick", "Hancock", "Haworth",
    "Hesch", "Hoffman", "Kassing", "Knutson", "Lawless",
    "Lawicki", "Mccord", "McCormack", "Miller", "Myers",
    "Nugent", "Ortiz", "Orwig", "Ory", "Paiser",
    "Pak", "Pettigrew", "Quinn", "Quizoz", "Ramachandran",
    "Resnick", "Sagar", "Schickowski", "Schiebel", "Sellon",
    "Severson", "Shaffer", "Solberg", "Soloman", "Sonderling",
    "Soukup", "Soulis", "Stahl", "Sweeney", "Tandy"
};

#endif // NAMES_H
